generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehPeriode
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_periode
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des périodes de stage
      filter:  ~
      form:    ~
      edit:
        title: Modifier une période de stage
      new:
        title: Nouvelle période de stage
