generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehEtudiant
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_etudiant
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        utilisateur: { label: Utilisateur, help: Utilisateur correspondant }
        sfGuardUser: { label: Étudiant, help: Utilisateur correspondant }
        promo_id: { label: Promotion }
        tel: { label: Téléphone }
        naissance: { label: Date de naissance }
        classement: { label: Classement (choix), help: Ordre de classement pour les choix dans la promo }
      list:
        title: Liste des étudiants
        display: [=sfGuardUser,  gesseh_promo, tel, naissance]
        sort: [promo_id, asc]
        max_per_page: 50
        actions:
          _new: { label: Ajouter }
          autoUpdatePromo: { label: Passage à la promo supérieure }
          deleteAncien: { label: Maintenance (hors promo) }
          importNew: { label: Importer }
        batch_actions:
          horsPromo: { label: Sortir des promos }
        object_actions:
          _edit: { label: Modifier }
        table_method: retrieveEtudiant
      filter:
        display: [promo_id]
      form:
        class: GessehEtudiantForm
        display: [promo_id, sfGuardUser, tel, naissance, classement]
      edit:
        title: Modifier %%sfGuardUser%%
        actions:
          _delete: { label: Supprimer }
          _list: { label: Retour à la liste }
          _save: { label: Enregistrer }
      new:
        title: Nouvel étudiant
        actions:
          _list: { label: Retour à la liste }
          _save: { label: Enregistrer }
          _save_and_add: { label: Ajouter un autre }
