generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehTerrain
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_terrain
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Terrains de stages
#        layout: stacked
        display: [gesseh_hopital, filiere, patron, is_active]
#        param: |
#          %%is_active%% %%filiere%% à %%gesseh_hopital%% (%%patron%%)
#          <small><em>%%localisation%%</em></small>
#          <small>Gardes %%gardes_lieu%% (%%gardes_horaires%%)</small>
#          <small>Astreintes %%astreintes_horaires%%</small>
        object_actions:
          edit: ~
        batch_actions: {}
        sort: [gesseh_hopital, asc]
      filter:
        display: [hopital_id, filiere, patron, is_active]
      form:
        display: display: [hopital_id, filiere, patron, is_active, localisation, gardes_lieu, gardes_horaires, astreintes_horaires]
      edit:
        title: Terrain : %%filiere%% (%%patron%%)
      new:     ~
