generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehTerrain
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_terrain
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        patron: { label: Chef de service }
        filiere: { label: Agrément, help: Type de terrain de stage }
        gesseh_filiere: { label: Agrément }
        is_active: { label: Actif?, help: Service utilisé dans la répartition des stages ? }
        hopital: { label: Hôpital }
      list:
        title: Terrains de stages
#        layout: stacked
        display: [gesseh_hopital, titre, patron, gesseh_filiere, total, postes_requis, is_active]
#        param: |
#          %%is_active%% %%filiere%% à %%gesseh_hopital%% (%%patron%%)
#          <small><em>%%localisation%%</em></small>
#          <small>Gardes %%gardes_lieu%% (%%gardes_horaires%%)</small>
#          <small>Astreintes %%astreintes_horaires%%</small>
        fields:
          gesseh_hopital: { label: Hôpital }
        object_actions:
          _edit: ~
        batch_actions: {}
        sort: [hopital_id, asc]
      filter:
        display: [hopital_id, filiere, patron, is_active]
      form:
#        display: display: [hopital_id, filiere, patron, is_active, localisation, gardes_lieu, gardes_horaires, astreintes_horaires]
      edit:
        title: Modification de %%filiere%% (%%patron%%)
      new:
        title: Nouveau terrain de stage
