<?php

/**
 * BaseGessehEtudiant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $prenom
 * @property integer $promo_id
 * @property string $email
 * @property GessehPromo $GessehPromo
 * @property Doctrine_Collection $GessehStage
 * 
 * @method string              getNom()         Returns the current record's "nom" value
 * @method string              getPrenom()      Returns the current record's "prenom" value
 * @method integer             getPromoId()     Returns the current record's "promo_id" value
 * @method string              getEmail()       Returns the current record's "email" value
 * @method GessehPromo         getGessehPromo() Returns the current record's "GessehPromo" value
 * @method Doctrine_Collection getGessehStage() Returns the current record's "GessehStage" collection
 * @method GessehEtudiant      setNom()         Sets the current record's "nom" value
 * @method GessehEtudiant      setPrenom()      Sets the current record's "prenom" value
 * @method GessehEtudiant      setPromoId()     Sets the current record's "promo_id" value
 * @method GessehEtudiant      setEmail()       Sets the current record's "email" value
 * @method GessehEtudiant      setGessehPromo() Sets the current record's "GessehPromo" value
 * @method GessehEtudiant      setGessehStage() Sets the current record's "GessehStage" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François 'Pilou' Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehEtudiant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_etudiant');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('prenom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('promo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehPromo', array(
             'local' => 'promo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('GessehStage', array(
             'local' => 'id',
             'foreign' => 'etudiant_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}