<?php

/**
 * BaseGessehChoix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $etudiant
 * @property integer $poste
 * @property integer $ordre
 * @property GessehEtudiant $GessehEtudiant
 * @property GessehTerrain $GessehTerrain
 * 
 * @method integer        getEtudiant()       Returns the current record's "etudiant" value
 * @method integer        getPoste()          Returns the current record's "poste" value
 * @method integer        getOrdre()          Returns the current record's "ordre" value
 * @method GessehEtudiant getGessehEtudiant() Returns the current record's "GessehEtudiant" value
 * @method GessehTerrain  getGessehTerrain()  Returns the current record's "GessehTerrain" value
 * @method GessehChoix    setEtudiant()       Sets the current record's "etudiant" value
 * @method GessehChoix    setPoste()          Sets the current record's "poste" value
 * @method GessehChoix    setOrdre()          Sets the current record's "ordre" value
 * @method GessehChoix    setGessehEtudiant() Sets the current record's "GessehEtudiant" value
 * @method GessehChoix    setGessehTerrain()  Sets the current record's "GessehTerrain" value
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehChoix extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_choix');
        $this->hasColumn('etudiant', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('poste', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ordre', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehEtudiant', array(
             'local' => 'etudiant',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GessehTerrain', array(
             'local' => 'poste',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}