<?php

/**
 * BaseGessehFormEval
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titre
 * @property Doctrine_Collection $GessehStage
 * @property Doctrine_Collection $GessehCritere
 * 
 * @method string              getTitre()         Returns the current record's "titre" value
 * @method Doctrine_Collection getGessehStage()   Returns the current record's "GessehStage" collection
 * @method Doctrine_Collection getGessehCritere() Returns the current record's "GessehCritere" collection
 * @method GessehFormEval      setTitre()         Sets the current record's "titre" value
 * @method GessehFormEval      setGessehStage()   Sets the current record's "GessehStage" collection
 * @method GessehFormEval      setGessehCritere() Sets the current record's "GessehCritere" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehFormEval extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_form_eval');
        $this->hasColumn('titre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GessehStage', array(
             'local' => 'id',
             'foreign' => 'form'));

        $this->hasMany('GessehCritere', array(
             'local' => 'id',
             'foreign' => 'form'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}