<?php

/**
 * BaseGessehHopital
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $adresse
 * @property string $telephone
 * @property string $web
 * @property Doctrine_Collection $GessehTerrain
 * 
 * @method string              getNom()           Returns the current record's "nom" value
 * @method string              getAdresse()       Returns the current record's "adresse" value
 * @method string              getTelephone()     Returns the current record's "telephone" value
 * @method string              getWeb()           Returns the current record's "web" value
 * @method Doctrine_Collection getGessehTerrain() Returns the current record's "GessehTerrain" collection
 * @method GessehHopital       setNom()           Sets the current record's "nom" value
 * @method GessehHopital       setAdresse()       Sets the current record's "adresse" value
 * @method GessehHopital       setTelephone()     Sets the current record's "telephone" value
 * @method GessehHopital       setWeb()           Sets the current record's "web" value
 * @method GessehHopital       setGessehTerrain() Sets the current record's "GessehTerrain" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehHopital extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_hopital');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('adresse', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('telephone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('web', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GessehTerrain', array(
             'local' => 'id',
             'foreign' => 'hopital_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}