<?php

/**
 * BaseGessehPromo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titre
 * @property integer $ordre
 * @property integer $form
 * @property GessehFormEval $GessehFormEval
 * @property Doctrine_Collection $GessehEtudiant
 * @property Doctrine_Collection $GessehReferent
 * 
 * @method string              getTitre()          Returns the current record's "titre" value
 * @method integer             getOrdre()          Returns the current record's "ordre" value
 * @method integer             getForm()           Returns the current record's "form" value
 * @method GessehFormEval      getGessehFormEval() Returns the current record's "GessehFormEval" value
 * @method Doctrine_Collection getGessehEtudiant() Returns the current record's "GessehEtudiant" collection
 * @method Doctrine_Collection getGessehReferent() Returns the current record's "GessehReferent" collection
 * @method GessehPromo         setTitre()          Sets the current record's "titre" value
 * @method GessehPromo         setOrdre()          Sets the current record's "ordre" value
 * @method GessehPromo         setForm()           Sets the current record's "form" value
 * @method GessehPromo         setGessehFormEval() Sets the current record's "GessehFormEval" value
 * @method GessehPromo         setGessehEtudiant() Sets the current record's "GessehEtudiant" collection
 * @method GessehPromo         setGessehReferent() Sets the current record's "GessehReferent" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehPromo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_promo');
        $this->hasColumn('titre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('ordre', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('form', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehFormEval', array(
             'local' => 'form',
             'foreign' => 'id'));

        $this->hasMany('GessehEtudiant', array(
             'local' => 'id',
             'foreign' => 'promo_id'));

        $this->hasMany('GessehReferent', array(
             'local' => 'id',
             'foreign' => 'promo'));
    }
}