<?php

/**
 * BaseGessehPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property blob $contenu
 * @property Doctrine_Collection $GessehTerrain
 * 
 * @method blob                getContenu()       Returns the current record's "contenu" value
 * @method Doctrine_Collection getGessehTerrain() Returns the current record's "GessehTerrain" collection
 * @method GessehPage          setContenu()       Sets the current record's "contenu" value
 * @method GessehPage          setGessehTerrain() Sets the current record's "GessehTerrain" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehPage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_page');
        $this->hasColumn('contenu', 'blob', null, array(
             'type' => 'blob',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GessehTerrain', array(
             'local' => 'id',
             'foreign' => 'page'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'format' => 'Y-m-d',
             ),
             'updated' => 
             array(
              'format' => 'Y-m-d',
             ),
             ));
        $this->actAs($timestampable0);
    }
}