<?php

/**
 * BaseGessehTerrain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hopital_id
 * @property string $filiere
 * @property string $patron
 * @property string $localisation
 * @property integer $form_id
 * @property boolean $is_active
 * @property GessehHopital $GessehHopital
 * @property GessehCritere $GessehCritere
 * @property Doctrine_Collection $GessehStage
 * 
 * @method integer             getHopitalId()     Returns the current record's "hopital_id" value
 * @method string              getFiliere()       Returns the current record's "filiere" value
 * @method string              getPatron()        Returns the current record's "patron" value
 * @method string              getLocalisation()  Returns the current record's "localisation" value
 * @method integer             getFormId()        Returns the current record's "form_id" value
 * @method boolean             getIsActive()      Returns the current record's "is_active" value
 * @method GessehHopital       getGessehHopital() Returns the current record's "GessehHopital" value
 * @method GessehCritere       getGessehCritere() Returns the current record's "GessehCritere" value
 * @method Doctrine_Collection getGessehStage()   Returns the current record's "GessehStage" collection
 * @method GessehTerrain       setHopitalId()     Sets the current record's "hopital_id" value
 * @method GessehTerrain       setFiliere()       Sets the current record's "filiere" value
 * @method GessehTerrain       setPatron()        Sets the current record's "patron" value
 * @method GessehTerrain       setLocalisation()  Sets the current record's "localisation" value
 * @method GessehTerrain       setFormId()        Sets the current record's "form_id" value
 * @method GessehTerrain       setIsActive()      Sets the current record's "is_active" value
 * @method GessehTerrain       setGessehHopital() Sets the current record's "GessehHopital" value
 * @method GessehTerrain       setGessehCritere() Sets the current record's "GessehCritere" value
 * @method GessehTerrain       setGessehStage()   Sets the current record's "GessehStage" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehTerrain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_terrain');
        $this->hasColumn('hopital_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('filiere', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('patron', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('localisation', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('form_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehHopital', array(
             'local' => 'hopital_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GessehCritere', array(
             'local' => 'form_id',
             'foreign' => 'form'));

        $this->hasMany('GessehStage', array(
             'local' => 'id',
             'foreign' => 'terrain_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}