<?php

/**
 * BaseGessehFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titre
 * @property integer $form
 * @property GessehFormEval $GessehFormEval
 * @property Doctrine_Collection $GessehTerrain
 * 
 * @method string              getTitre()          Returns the current record's "titre" value
 * @method integer             getForm()           Returns the current record's "form" value
 * @method GessehFormEval      getGessehFormEval() Returns the current record's "GessehFormEval" value
 * @method Doctrine_Collection getGessehTerrain()  Returns the current record's "GessehTerrain" collection
 * @method GessehFiliere       setTitre()          Sets the current record's "titre" value
 * @method GessehFiliere       setForm()           Sets the current record's "form" value
 * @method GessehFiliere       setGessehFormEval() Sets the current record's "GessehFormEval" value
 * @method GessehFiliere       setGessehTerrain()  Sets the current record's "GessehTerrain" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_filiere');
        $this->hasColumn('titre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('form', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehFormEval', array(
             'local' => 'form',
             'foreign' => 'id'));

        $this->hasMany('GessehTerrain', array(
             'local' => 'id',
             'foreign' => 'filiere'));
    }
}