<?php

/**
 * BaseGessehEtudiant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $prenom
 * @property integer $promo_id
 * @property string $email
 * @property string $token_mail
 * @property string $tel
 * @property GessehPromo $GessehPromo
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $GessehStage
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNom()         Returns the current record's "nom" value
 * @method string              getPrenom()      Returns the current record's "prenom" value
 * @method integer             getPromoId()     Returns the current record's "promo_id" value
 * @method string              getEmail()       Returns the current record's "email" value
 * @method string              getTokenMail()   Returns the current record's "token_mail" value
 * @method string              getTel()         Returns the current record's "tel" value
 * @method GessehPromo         getGessehPromo() Returns the current record's "GessehPromo" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getGessehStage() Returns the current record's "GessehStage" collection
 * @method GessehEtudiant      setId()          Sets the current record's "id" value
 * @method GessehEtudiant      setNom()         Sets the current record's "nom" value
 * @method GessehEtudiant      setPrenom()      Sets the current record's "prenom" value
 * @method GessehEtudiant      setPromoId()     Sets the current record's "promo_id" value
 * @method GessehEtudiant      setEmail()       Sets the current record's "email" value
 * @method GessehEtudiant      setTokenMail()   Sets the current record's "token_mail" value
 * @method GessehEtudiant      setTel()         Sets the current record's "tel" value
 * @method GessehEtudiant      setGessehPromo() Sets the current record's "GessehPromo" value
 * @method GessehEtudiant      setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method GessehEtudiant      setGessehStage() Sets the current record's "GessehStage" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François 'Pilou' Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehEtudiant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_etudiant');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('prenom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('promo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('token_mail', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tel', 'string', 14, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 14,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehPromo', array(
             'local' => 'promo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'username'));

        $this->hasMany('GessehStage', array(
             'local' => 'id',
             'foreign' => 'etudiant_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}