<?php

/**
 * BaseGessehPromo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titre
 * @property Doctrine_Collection $GessehEtudiant
 * 
 * @method string              getTitre()          Returns the current record's "titre" value
 * @method Doctrine_Collection getGessehEtudiant() Returns the current record's "GessehEtudiant" collection
 * @method GessehPromo         setTitre()          Sets the current record's "titre" value
 * @method GessehPromo         setGessehEtudiant() Sets the current record's "GessehEtudiant" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehPromo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_promo');
        $this->hasColumn('titre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GessehEtudiant', array(
             'local' => 'id',
             'foreign' => 'promo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}