<?php

/**
 * BaseGessehReferent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $utilisateur
 * @property integer $promo
 * @property string $tel
 * @property string $divers
 * @property GessehPromo $GessehPromo
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer        getUtilisateur() Returns the current record's "utilisateur" value
 * @method integer        getPromo()       Returns the current record's "promo" value
 * @method string         getTel()         Returns the current record's "tel" value
 * @method string         getDivers()      Returns the current record's "divers" value
 * @method GessehPromo    getGessehPromo() Returns the current record's "GessehPromo" value
 * @method sfGuardUser    getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method GessehReferent setUtilisateur() Sets the current record's "utilisateur" value
 * @method GessehReferent setPromo()       Sets the current record's "promo" value
 * @method GessehReferent setTel()         Sets the current record's "tel" value
 * @method GessehReferent setDivers()      Sets the current record's "divers" value
 * @method GessehReferent setGessehPromo() Sets the current record's "GessehPromo" value
 * @method GessehReferent setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehReferent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_referent');
        $this->hasColumn('utilisateur', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('promo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tel', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('divers', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehPromo', array(
             'local' => 'promo',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'utilisateur',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}