<?php

/**
 * BaseGessehTerrain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hopital_id
 * @property string $titre
 * @property integer $filiere
 * @property string $patron
 * @property integer $total
 * @property blob $page
 * @property boolean $is_active
 * @property GessehHopital $GessehHopital
 * @property GessehFiliere $GessehFiliere
 * @property Doctrine_Collection $GessehStage
 * @property Doctrine_Collection $GessehChoix
 * @property Doctrine_Collection $GessehSimulation
 * 
 * @method integer             getHopitalId()        Returns the current record's "hopital_id" value
 * @method string              getTitre()            Returns the current record's "titre" value
 * @method integer             getFiliere()          Returns the current record's "filiere" value
 * @method string              getPatron()           Returns the current record's "patron" value
 * @method integer             getTotal()            Returns the current record's "total" value
 * @method blob                getPage()             Returns the current record's "page" value
 * @method boolean             getIsActive()         Returns the current record's "is_active" value
 * @method GessehHopital       getGessehHopital()    Returns the current record's "GessehHopital" value
 * @method GessehFiliere       getGessehFiliere()    Returns the current record's "GessehFiliere" value
 * @method Doctrine_Collection getGessehStage()      Returns the current record's "GessehStage" collection
 * @method Doctrine_Collection getGessehChoix()      Returns the current record's "GessehChoix" collection
 * @method Doctrine_Collection getGessehSimulation() Returns the current record's "GessehSimulation" collection
 * @method GessehTerrain       setHopitalId()        Sets the current record's "hopital_id" value
 * @method GessehTerrain       setTitre()            Sets the current record's "titre" value
 * @method GessehTerrain       setFiliere()          Sets the current record's "filiere" value
 * @method GessehTerrain       setPatron()           Sets the current record's "patron" value
 * @method GessehTerrain       setTotal()            Sets the current record's "total" value
 * @method GessehTerrain       setPage()             Sets the current record's "page" value
 * @method GessehTerrain       setIsActive()         Sets the current record's "is_active" value
 * @method GessehTerrain       setGessehHopital()    Sets the current record's "GessehHopital" value
 * @method GessehTerrain       setGessehFiliere()    Sets the current record's "GessehFiliere" value
 * @method GessehTerrain       setGessehStage()      Sets the current record's "GessehStage" collection
 * @method GessehTerrain       setGessehChoix()      Sets the current record's "GessehChoix" collection
 * @method GessehTerrain       setGessehSimulation() Sets the current record's "GessehSimulation" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehTerrain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_terrain');
        $this->hasColumn('hopital_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('titre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('filiere', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('patron', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('total', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 3,
             ));
        $this->hasColumn('page', 'blob', null, array(
             'type' => 'blob',
             'notnull' => false,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehHopital', array(
             'local' => 'hopital_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GessehFiliere', array(
             'local' => 'filiere',
             'foreign' => 'id'));

        $this->hasMany('GessehStage', array(
             'local' => 'id',
             'foreign' => 'terrain_id'));

        $this->hasMany('GessehChoix', array(
             'local' => 'id',
             'foreign' => 'poste'));

        $this->hasMany('GessehSimulation', array(
             'local' => 'id',
             'foreign' => 'poste'));
    }
}