<?php

/**
 * BaseGessehPromo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titre
 * @property integer $ordre
 * @property Doctrine_Collection $GessehTerrainRule
 * @property Doctrine_Collection $GessehEtudiant
 * 
 * @method string              getTitre()             Returns the current record's "titre" value
 * @method integer             getOrdre()             Returns the current record's "ordre" value
 * @method Doctrine_Collection getGessehTerrainRule() Returns the current record's "GessehTerrainRule" collection
 * @method Doctrine_Collection getGessehEtudiant()    Returns the current record's "GessehEtudiant" collection
 * @method GessehPromo         setTitre()             Sets the current record's "titre" value
 * @method GessehPromo         setOrdre()             Sets the current record's "ordre" value
 * @method GessehPromo         setGessehTerrainRule() Sets the current record's "GessehTerrainRule" collection
 * @method GessehPromo         setGessehEtudiant()    Sets the current record's "GessehEtudiant" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François 'Pilou' Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehPromo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_promo');
        $this->hasColumn('titre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ordre', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GessehTerrainRule', array(
             'local' => 'id',
             'foreign' => 'promo'));

        $this->hasMany('GessehEtudiant', array(
             'local' => 'id',
             'foreign' => 'promo_id'));
    }
}