<?php

/**
 * BaseCopisimSimulation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $etudiant
 * @property integer $poste
 * @property integer $reste
 * @property boolean $absent
 * @property GessehEtudiant $GessehEtudiant
 * @property GessehTerrain $GessehTerrain
 * 
 * @method integer           getEtudiant()       Returns the current record's "etudiant" value
 * @method integer           getPoste()          Returns the current record's "poste" value
 * @method integer           getReste()          Returns the current record's "reste" value
 * @method boolean           getAbsent()         Returns the current record's "absent" value
 * @method GessehEtudiant    getGessehEtudiant() Returns the current record's "GessehEtudiant" value
 * @method GessehTerrain     getGessehTerrain()  Returns the current record's "GessehTerrain" value
 * @method CopisimSimulation setEtudiant()       Sets the current record's "etudiant" value
 * @method CopisimSimulation setPoste()          Sets the current record's "poste" value
 * @method CopisimSimulation setReste()          Sets the current record's "reste" value
 * @method CopisimSimulation setAbsent()         Sets the current record's "absent" value
 * @method CopisimSimulation setGessehEtudiant() Sets the current record's "GessehEtudiant" value
 * @method CopisimSimulation setGessehTerrain()  Sets the current record's "GessehTerrain" value
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCopisimSimulation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_simulation');
        $this->hasColumn('etudiant', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('poste', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('reste', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('absent', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehEtudiant', array(
             'local' => 'etudiant',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GessehTerrain', array(
             'local' => 'poste',
             'foreign' => 'id'));
    }
}