<?php

/**
 * BaseGessehEval
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stage_id
 * @property integer $critere_id
 * @property string $valeur
 * @property  $created_at
 * @property GessehStage $GessehStage
 * @property GessehCritere $GessehCritere
 * 
 * @method integer       getStageId()       Returns the current record's "stage_id" value
 * @method integer       getCritereId()     Returns the current record's "critere_id" value
 * @method string        getValeur()        Returns the current record's "valeur" value
 * @method GessehStage   getGessehStage()   Returns the current record's "GessehStage" value
 * @method GessehCritere getGessehCritere() Returns the current record's "GessehCritere" value
 * @method GessehEval    setStageId()       Sets the current record's "stage_id" value
 * @method GessehEval    setCritereId()     Sets the current record's "critere_id" value
 * @method GessehEval    setValeur()        Sets the current record's "valeur" value
 * @method GessehEval    setGessehStage()   Sets the current record's "GessehStage" value
 * @method GessehEval    setGessehCritere() Sets the current record's "GessehCritere" value
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehEval extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_eval');
        $this->hasColumn('stage_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('critere_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('valeur', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('created_at', '', null);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehStage', array(
             'local' => 'stage_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GessehCritere', array(
             'local' => 'critere_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}