<?php

/**
 * BaseGessehPeriode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $debut
 * @property date $fin
 * @property Doctrine_Collection $GessehStage
 * 
 * @method date                getDebut()       Returns the current record's "debut" value
 * @method date                getFin()         Returns the current record's "fin" value
 * @method Doctrine_Collection getGessehStage() Returns the current record's "GessehStage" collection
 * @method GessehPeriode       setDebut()       Sets the current record's "debut" value
 * @method GessehPeriode       setFin()         Sets the current record's "fin" value
 * @method GessehPeriode       setGessehStage() Sets the current record's "GessehStage" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehPeriode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_periode');
        $this->hasColumn('debut', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fin', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GessehStage', array(
             'local' => 'id',
             'foreign' => 'periode_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}