<?php

/**
 * BaseGessehHopital
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titre
 * @property string $adresse
 * @property string $telephone
 * @property string $web
 * @property blob $page
 * @property Doctrine_Collection $GessehTerrain
 * 
 * @method string              getTitre()         Returns the current record's "titre" value
 * @method string              getAdresse()       Returns the current record's "adresse" value
 * @method string              getTelephone()     Returns the current record's "telephone" value
 * @method string              getWeb()           Returns the current record's "web" value
 * @method blob                getPage()          Returns the current record's "page" value
 * @method Doctrine_Collection getGessehTerrain() Returns the current record's "GessehTerrain" collection
 * @method GessehHopital       setTitre()         Sets the current record's "titre" value
 * @method GessehHopital       setAdresse()       Sets the current record's "adresse" value
 * @method GessehHopital       setTelephone()     Sets the current record's "telephone" value
 * @method GessehHopital       setWeb()           Sets the current record's "web" value
 * @method GessehHopital       setPage()          Sets the current record's "page" value
 * @method GessehHopital       setGessehTerrain() Sets the current record's "GessehTerrain" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehHopital extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_hopital');
        $this->hasColumn('titre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('adresse', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('telephone', 'string', 14, array(
             'type' => 'string',
             'length' => 14,
             ));
        $this->hasColumn('web', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('page', 'blob', null, array(
             'type' => 'blob',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GessehTerrain', array(
             'local' => 'id',
             'foreign' => 'hopital_id'));
    }
}