<?php

/**
 * BaseGessehTerrain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hopital_id
 * @property string $filiere
 * @property string $patron
 * @property string $localisation
 * @property string $gardes_lieu
 * @property string $gardes_horaires
 * @property string $astreintes_horaires
 * @property boolean $is_active
 * @property GessehHopital $GessehHopital
 * @property Doctrine_Collection $GessehStage
 * 
 * @method integer             getHopitalId()           Returns the current record's "hopital_id" value
 * @method string              getFiliere()             Returns the current record's "filiere" value
 * @method string              getPatron()              Returns the current record's "patron" value
 * @method string              getLocalisation()        Returns the current record's "localisation" value
 * @method string              getGardesLieu()          Returns the current record's "gardes_lieu" value
 * @method string              getGardesHoraires()      Returns the current record's "gardes_horaires" value
 * @method string              getAstreintesHoraires()  Returns the current record's "astreintes_horaires" value
 * @method boolean             getIsActive()            Returns the current record's "is_active" value
 * @method GessehHopital       getGessehHopital()       Returns the current record's "GessehHopital" value
 * @method Doctrine_Collection getGessehStage()         Returns the current record's "GessehStage" collection
 * @method GessehTerrain       setHopitalId()           Sets the current record's "hopital_id" value
 * @method GessehTerrain       setFiliere()             Sets the current record's "filiere" value
 * @method GessehTerrain       setPatron()              Sets the current record's "patron" value
 * @method GessehTerrain       setLocalisation()        Sets the current record's "localisation" value
 * @method GessehTerrain       setGardesLieu()          Sets the current record's "gardes_lieu" value
 * @method GessehTerrain       setGardesHoraires()      Sets the current record's "gardes_horaires" value
 * @method GessehTerrain       setAstreintesHoraires()  Sets the current record's "astreintes_horaires" value
 * @method GessehTerrain       setIsActive()            Sets the current record's "is_active" value
 * @method GessehTerrain       setGessehHopital()       Sets the current record's "GessehHopital" value
 * @method GessehTerrain       setGessehStage()         Sets the current record's "GessehStage" collection
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGessehTerrain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gesseh_terrain');
        $this->hasColumn('hopital_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('filiere', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('patron', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('localisation', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('gardes_lieu', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('gardes_horaires', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('astreintes_horaires', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GessehHopital', array(
             'local' => 'hopital_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('GessehStage', array(
             'local' => 'id',
             'foreign' => 'terrain_id'));
    }
}