generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehHopital
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_hopital
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        telephone: { label: Téléphone }
        web: { label: Site web }
      list:
        title: Liste des hôpitaux
        display: [titre, adresse, telephone, web]
        sort: [titre, asc]
        batch_actions: {}
      filter:
        class: false
      form:    ~
      edit:
        title: Editer %%titre%%
        display: [titre, adresse, telephone, web]
      new:
        title: Nouvel hôpital
        display: [titre, adresse, telephone, web]
