<?php

namespace Gesseh\SimulationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SimulPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimulPeriodRepository extends EntityRepository
{
  public function isSimulationActive()
  {
    $query = $this->createQueryBuilder('p')
                  ->where('p.begin < :now')
                  ->andWhere('p.end > :now')
                    ->setParameter('now', new \DateTime('now'));

    if ($query->getQuery()->getResult())
      return true;
    else
      return false;
  }
}
