<?php

namespace Gesseh\SimulationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SimulPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimulPeriodRepository extends EntityRepository
{
  public function isSimulationActive()
  {
    $query = $this->createQueryBuilder('p')
                  ->where('p.begin < :now')
                  ->andWhere('p.end > :now')
                    ->setParameter('now', new \DateTime('now'));

    if ($query->getQuery()->getResult())
      return true;
    else
      return false;
  }

  public function getLastActive()
  {
    $query = $this->createQueryBuilder('p')
                  ->join('p.period', 'q')
                  ->addSelect('q')
                  ->where('p.end < :now')
                  ->andWhere('q.begin > :now')
                    ->setParameter('now', new \DateTime('now'))
                  ->orderBy('p.end', 'desc')
                  ->setMaxResults(1);

    return $query->getQuery()->getSingleResult();
  }
}
