<?php

namespace Gesseh\SimulationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends EntityRepository
{
  public function getWishQuery()
  {
    return $this->createQueryBuilder('w')
                ->join('w.student', 's')
                ->join('w.department', 'd')
                ->join('d.hospital', 'h')
                ->join('d.sector', 't')
                ->addSelect('s')
                ->addSelect('d')
                ->addSelect('h')
                ->addSelect('t');
  }

  public function getByStudent($student_id)
  {
    $query = $this->getWishQuery();
    $query->where('s.id = :student')
            ->setParameter('student', $student_id)
          ->addOrderBy('w.rank', 'asc');

    return $query->getQuery()->getResult();
  }
}
