<?php

/**
 * CopisimSimulationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CopisimSimulationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CopisimSimulationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CopisimSimulation');
    }
}