<?php

/**
 * GessehReferentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GessehReferentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GessehReferentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GessehReferent');
    }
}