<?php

/**
 * GessehChoixTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GessehChoixTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GessehChoixTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GessehChoix');
    }
}