<?php

/**
 * GessehSimulationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GessehSimulationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GessehSimulationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GessehSimulation');
    }
}