<?php

/**
 * GessehFormEval
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François 'Pilou' Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GessehFormEval extends BaseGessehFormEval
{
  /* Magic Method : Affiche le titre pour le formulaire d'évaluation */
  public function __toString()
  {
    return sprintf('%s', $this->getTitre());
  }

  public function addCriteria()
  {
    $criteria = new GessehCritere();
    $criteria->setForm($this->getId());
    $criteria->setTitre("Nouveau critère");
    $criteria->setOrdre(Doctrine::getTable('GessehCritere')->getMaxOrderForForm($this->getId()));
    $criteria->setType('text');

    return $criteria->save();
  }

}
