<?php

/**
 * GessehTerrain
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François "Pilou" Angrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GessehTerrain extends BaseGessehTerrain
{
  public function __toString()
  {
    if ($this->getId() == null)
      return "Aucun";
    else
      return sprintf('%s : %s (%s)', $this->getGessehHopital()->getTitre(), $this->getTitre(), $this->getPatron());
  }

  /* Retourne le nombre de 1er voeux pour le terrain */
  public function getPostesRequis()
  {
    $voeux = Doctrine::getTable('GessehChoix')->getFirstChoixByTerrain($this->getId());

    return $voeux->count();
  }

}
