<?php

/**
 * GessehFiliereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GessehFiliereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GessehFiliereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GessehFiliere');
    }
}