<?php

/**
 * GessehEtudiant
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GessehEtudiant extends BaseGessehEtudiant
{
  /* Magic Method : Affiche Nom Prenom à l'appel d'Etudiant */
  public function __toString()
  {
    return sprintf('%s %s', $this->getSfGuardUser()->getLastName(), $this->getSfGuardUser()->getFirstName());
  }

  /* Depreciated : Envoie un jeton de confirmation de l'adresse email */
  public function sendMailValidation($email)
  {
    $user = sfContext::getInstance()->getUser()->getUsername();
    $url = csSettings::get('baseurl');
    $token = sha1(sfContext::getInstance()->getUser()->getUsername().$email);
    $message = sfContext::getInstance()->getMailer()->compose(
      array(csSettings::get('email') => csSettings::get('email_nom')),
      $email,
      '['.csSettings::get('email_prefixe').'] Validation de votre nouvelle adresse mail',
      <<<EOF
      Bonjour,

      Vous venez de changer votre adresse mail sur le gestionnaire d'évaluations de la faculté. Pour valider le changement d'adresse e-mail, nous vous prions de bien vouloir aller sur le lien suivant :

{$url}etudiant/test/{$user}/{$token}

      Merci.

      L'administration.
      Ce message a été généré automatiquement, merci de ne pas y répondre.
EOF
      );
      sfContext::getInstance()->getMailer()->send($message);
  }

}
