<?php

/**
 * GessehChoixTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GessehChoixTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GessehChoixTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GessehChoix');
    }

    /* Récupère la liste des voeux de l'étudiant */
    public function getEtudiantChoix($etudiant)
    {
      $q = Doctrine_Query::create()
        ->from('GessehChoix a')
//        ->leftJoin('a.Gesseh b')
//        ->leftJoin('b.GessehHopital c')
        ->leftJoin('a.GessehTerrain d')
        ->where('a.etudiant = ?', $etudiant)
        ->andWhere('a.ordre != ?', '0')
        ->orderBy('a.ordre');

      return $q->execute();
    }

    /* Récupère l'ordre du choix en question */
    private function getCurrentChoiceOrder($id)
    {
      $c = Doctrine_Query::create()
        ->from('GessehChoix a')
        ->select('a.ordre')
        ->where('id = ?', $id)
        ->limit(1)
        ->fetchOne();

      return $c->getOrdre();
    }

    /* Monte un voeu dans la liste et descend le précédent */
    public function setEtudiantChoixUp($etudiant, $choix)
    {
      $cur = $this->getCurrentChoiceOrder($choix);
      $prev = $cur - 1;

      if($cur > 1){
        Doctrine_Query::create()
          ->update('GessehChoix a')
          ->set('a.ordre', '?', $cur)
          ->where('a.etudiant = ?', $etudiant)
          ->andWhere('a.ordre = ?', $prev)
          ->limit(1)
          ->execute();

        Doctrine_Query::create()
          ->update('GessehChoix a')
          ->set('a.ordre', '?', $prev)
          ->where('a.id = ?', $choix)
          ->limit(1)
          ->execute();
      }
    }

    /* Descend un voeu dans la liste et monte le suivant */
    public function setEtudiantChoixDown($etudiant, $choix)
    {
      $cur = $this->getCurrentChoiceOrder($choix);
      $next = $cur + 1;

      Doctrine_Query::create()
        ->update('GessehChoix a')
        ->set('a.ordre', '?', $cur)
        ->where('a.etudiant = ?', $etudiant)
        ->andWhere('a.ordre = ?', $next)
        ->limit(1)
        ->execute();

      Doctrine_Query::create()
        ->update('GessehChoix a')
        ->set('a.ordre', '?', $next)
        ->where('a.id = ?', $choix)
        ->limit(1)
        ->execute();
    }

    /* Supprime un voeu de la liste (mais pas de la base) */
    public function setEtudiantChoixDel($etudiant, $choix)
    {
      Doctrine_Query::create()
        ->update('GessehChoix a')
        ->set('a.ordre', '?', '0')
        ->where('a.id = ?', $choix)
        ->limit(1)
        ->execute();
    }

    /* Descend tous les voeux de l'étudiant d'un cran */
    public function cascadeEtudiantChoixDown($etudiant)
    {
      $q = Doctrine_Query::create()
        ->update('GessehChoix a')
        ->set('a.ordre', 'a.ordre + 1')
        ->where('a.etudiant = ?', $etudiant)
        ->andWhere('a.ordre > ?', '0')
        ->execute();
    }

    /* Teste la présence d'un voeu dans la base */
    public function isAlreadySaved($etudiant, $poste)
    {
      $q = Doctrine_Query::create()
        ->from('GessehChoix a')
        ->where('etudiant = ?', $etudiant)
        ->andWhere('poste = ?', $poste)
        ->limit(1);

      if($choix = $q->fetchOne())
        return $choix;
      else
        return false;
    }

    /* Récupère tous les choix similaires des autres étudiants choissisant avant l'étudiant */
    public function getMemeChoix($classement, $poste)
    {
      $q = Doctrine_Query::create()
        ->from('GessehChoix a')
        ->leftJoin('a.GessehEtudiant b')
        ->where('b.classement < ?', $classement)
// Attention : ajouter une clause de sélection des étudiants choisissant avant avec GessehSimulation */
        ->andWhere('a.poste = ?', $poste)
        ->orderBy('b.classement asc');

      return $q->execute();
    }

    /* Retourne la liste des premiers voeux d'un terrain */
    public function getFirstChoixByTerrain($id_terrain)
    {
      $q = Doctrine_Query::create()
        ->from('GessehChoix a')
        ->where('a.ordre = ?', '1')
        ->andWhere('a.poste = ?', $id_terrain);

      return $q->execute();
    }

    /* Vide la table de voeux */
    public function cleanChoixTable()
    {
      $q = Doctrine_Query::create()
        ->delete()
        ->from('GessehChoix a');

      return $q->execute();
    }
}
