<?php

/**
 * GessehStage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GessehStage extends BaseGessehStage
{
  public function __toString()
  {
    return sprintf('%s %s : %s du %s au %s', $this->getGessehEtudiant()->getNom(), $this->getGessehEtudiant()->getPrenom(), $this->getGessehTerrain()->getFiliere(), $this->getGessehPeriode()->getDebut(), $this->getGessehPeriode()->getFin());
  }

}
