<?php

/**
 * GessehSimulation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-François Pilou Angrand <tmp@angrand.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GessehSimulation extends BaseGessehSimulation
{
}
