<?php

/**
 * GessehPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GessehPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GessehPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GessehPage');
    }
}