<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  /* Enregistrement personnalisé d'un utilisateur */
  public function save (Doctrine_Connection $conn = null)
  {
    if ($this->getPassword() == null) {
      $this->setPassword($this->generatePassword(8));
    }

    if ($this->getUsername() == null) {
      $this->setUsername($this->generateUsername());
    }

    /* Paramètres prédéfinis pour l'enregistrement d'un étudiant */
    if ($this->getId() != null) {
      if ($etudiant = Doctrine::getTable('GessehEtudiant')->findOneByUtilisateur($this->getId())) {
        if ($etudiant->getPromoId() == Doctrine::getTable('GessehPromo')->findOneByActive(false)->getId()) {
          $this->setIsActive(false);
        } else {
          $this->setIsActive(true);
        }
        if (!$this->hasGroup('etudiant')) {
          $this->addGroupByName('etudiant');
        }
      }
/*    } else {
      if (isset($_SESSION)) {
        $this->sendMailToUser();
      } */
    }

    return parent::save($conn);
  }

  /* Auto-génération d'un mot de passe */
  private function generatePassword ($length)
  {
    $characters = array ('a','z','e','r','t','y','u','p','q','s','d','f','g','h','j','k','m','w','x','c','v','b','n','2','3','4','5','6','7','8','9','A','Z','E','R','T','Y','U','P','S','D','F','G','H','J','K','L','M','W','X','C','V','B','N');

    $password = '';

    for ($i = 0 ; $i < $length ; $i++) {
      $rand = array_rand($characters);
      $password .= $characters[$rand];
    }

    return $password;
  }

  /* Auto-génération du nom d'utilisateur en fonction du nom de l'étudiant */
  private function generateUsername()
  {
    $nom = $this->getLastName();
    $prenom = $this->getFirstName();

    return strtolower(substr($prenom, 0, 2) . substr($nom, 0, 5));
  }

/*  public function sendMailToUser()
  {
    $url = sfContext::getInstance()->getRequest()->getRelativeRootUrl();
    $nom = $this->getFirstName().' '.$this->getLastName();
    $username = $this->getUsername();
    $email = $this->getEmailAddress();
    if ($emailto = csSettings::get('email') == null) {
      $emailto = $email;
    } else {
      $emailto = csSettings::get('email');
    }

    $message = sfContext::getInstance()->getMailer()->compose(
      array('noreply@medlibre.fr' => csSettings::get('email_nom')),
      $emailto,
      '[' . csSettings::get('email_prefixe') . '] Information sur votre compte utilisateur',
      <<<EOF
      Bonjour {$nom},

      Votre compte utilisateur sur le gestionnaire de stages hospitaliers a été mis à jour. Voici un récapitulatif des informations dont vous aurez besoin pour vous connecter.

      URL du site : http://{$url}
      Compte : {$username}
      Adresse email : {$email}

      Si vous ne vous souvenez pas de votre mot de passe, vous pouvez le réinitialiser ici : http://{$url}/web/guard/forgot_password

      Ce message a été automatiquement généré, veuillez ne pas y répondre. Merci.
EOF
    );

    sfContext::getInstance()->getMailer()->send($message);
  } */
}
