<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gesseh
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  /* Enregistrement personnalisé d'un utilisateur */
  public function save (Doctrine_Connection $conn = null)
  {
    /* Paramètres prédéfinis pour l'enregistrement d'un étudiant */
    if ($this->getId() != null) {
      if ($etudiant = Doctrine::getTable('GessehEtudiant')->findOneByUtilisateur($this->getId())) {
        if ($etudiant->getPromoId() == Doctrine::getTable('GessehPromo')->findOneByActive(false)->getId()) {
          $this->setIsActive(false);
        } else {
          $this->setIsActive(true);
        }
        if (!$this->hasGroup('etudiant')) {
          $this->addGroupByName('etudiant');
        }
      }
    }

    if ($this->getPassword() == null) {
      $this->setPassword($this->generatePassword(8));
    }

    return parent::save($conn);
  }

  /* Auto-génération d'un mot de passe */
  private function generatePassword ($length)
  {
    $characters = array ('a','z','e','r','t','y','u','p','q','s','d','f','g','h','j','k','m','w','x','c','v','b','n','2','3','4','5','6','7','8','9','A','Z','E','R','T','Y','U','P','S','D','F','G','H','J','K','L','M','W','X','C','V','B','N');

    $password = '';

    for ($i = 0 ; $i < $length ; $i++) {
      $rand = array_rand($characters);
      $password .= $characters[$rand];
    }

    return $password;
  }
}
