imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @GessehCoreBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines:        ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    session:
      cookie_lifetime: 3600
    fragments:            ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping:                true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
#   spool:     { type: memory }

#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false

fos_user:
  db_driver:     orm
  firewall_name: main
#  use_listener:  false
  user_class:    Gesseh\UserBundle\Entity\User
  from_email:
    address:     %mailer_mail%
    sender_name: Admin Gesseh

kdb_parameters:
  db_driver: orm
  class:     Gesseh\ParameterBundle\Entity\Parameter

knp_paginator:
  page_range: 5                       # default page range used in pagination control
  default_options:
    page_name:           page         # page query parameter name
    sort_field_name:     sort         # sort field query parameter name
    sort_direction_name: direction    # sort direction query parameter name
    distinct:            true         # ensure distinct results, useful when ORM queries are using GROUP BY statements
    filter_field_name:   filterField
    filter_value_name:   filterValue
  template:
    pagination: KnpPaginatorBundle:Pagination:sliding.html.twig       # sliding pagination controls template
    filtration: KnpPaginatorBundle:Pagination:filtration.html.twig
    sortable:   KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

knp_snappy:
    pdf:
        enabled: true
        binary:  "%kernel.root_dir%/../vendor/google/wkhtmltopdf-i386/wkhtmltopdf-i386"
        options: []
    image:
        enabled: false

stfalcon_tinymce:
  include_jquery: true
  tinymce_jquery: true
  textarea_class: "tinymce"
  theme:
    simple:
      mode:                             "textareas"
      theme:                            "advanced"
      theme_advanced_buttons1:          "mylistbox,mysplitbutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink"
      theme_advanced_buttons2:           ""
      theme_advanced_buttons3:           ""
      theme_advanced_toolbar_location:   "top"
      theme_advanced_toolbar_align:      "left"
      theme_advanced_statusbar_location: "bottom"
      plugins:                           "fullscreen"
      theme_advanced_buttons1_add:       "fullscreen"
      language:                          %locale%
    advanced:
      theme: "advanced"
      plugins: "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template"
      theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect"
      theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor"
      theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen"
      theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak"
      theme_advanced_toolbar_location: "top"
      theme_advanced_toolbar_align: "left"
      theme_advanced_statusbar_location: "bottom"
      theme_advanced_resizing: true
    medium:
      mode: "textareas"
      theme: "advanced"
      plugins: "table,advhr,advlink,paste,xhtmlxtras,spellchecker"
      theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,forecolor,backcolor,|,hr,removeformat,|,sub,sup,|,spellchecker"
      theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,bullist,numlist,|,undo,redo,|,link,unlink,anchor,cleanup,code,|,tablecontrols"
      theme_advanced_buttons3: ""
      theme_advanced_toolbar_location: "top"
      theme_advanced_toolbar_align: "left"
      theme_advanced_statusbar_location: ""
      paste_auto_cleanup_on_paste: true
      spellchecker_languages: "+English=en,Dutch=nl"
    bbcode:
      mode: "none"
      theme: "advanced"
      plugins: "bbcode"
      theme_advanced_buttons1: "bold,italic,underline,undo,redo,link,unlink,image,forecolor,styleselect,removeformat,cleanup,code"
      theme_advanced_buttons2: ""
      theme_advanced_buttons3: ""
      theme_advanced_toolbar_location: "bottom"
      theme_advanced_toolbar_align: "center"
      theme_advanced_styles: "Code=codeStyle;Quote=quoteStyle"
      entity_encoding: "raw"
      add_unload_trigger: false
      remove_linebreaks: false
      inline_styles: false
      convert_fonts_to_spans: false
