GessehUserBundle:
    resource: "@GessehUserBundle/Controller/"
    type:     annotation
    prefix:   /

GessehCoreBundle:
    resource: "@GessehCoreBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
