GessehUserBundle:
  resource: "@GessehUserBundle/Controller/"
  type:     annotation

GessehCoreBundle:
  resource: "@GessehCoreBundle/Controller/"
  type:     annotation

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /reset

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /u

