gesseh_import:
    resource: "@GessehImportBundle/Controller/"
    type:     annotation
    prefix:   /

gesseh_register:
    resource: "@GessehRegisterBundle/Controller/"
    type:     annotation
    prefix:   /

#GessehMigrateOldDbBundle:
#    resource: "@GessehMigrateOldDbBundle/Controller/"
#    type:     annotation
#    prefix:   /

GessehEvaluationBundle:
    resource: "@GessehEvaluationBundle/Controller/"
    type:     annotation
    prefix:   /

GessehSimulationBundle:
    resource: "@GessehSimulationBundle/Controller/"
    type:     annotation
    prefix:   /

GessehParameterBundle:
    resource: "@GessehParameterBundle/Controller/"
    type:     annotation
    prefix:   /

GessehUserBundle:
  resource: "@GessehUserBundle/Controller/"
  type:     annotation

GessehCoreBundle:
  resource: "@GessehCoreBundle/Controller/"
  type:     annotation

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /reset

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /user

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /fos

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register
