security:
    encoders:
      "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_STUDENT, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      fos_userbundle:
        id: fos_user.user_manager

    firewalls:
      main:
        pattern:         ^/
        form_login:
          provider:      fos_userbundle
          csrf_provider: form.csrf_provider
        logout:          true
        anonymous:       true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/f/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/u/, role: ROLE_STUDENT }
