generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehFormEval
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_form_eval
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des formulaires d'évaluation
        display: [titre, updated_at]
        batch_actions: {}
      filter:
        class: false
      form:    ~
      edit:
        title: Modifier %%titre%%
      new:
        title: Nouveau formulaire d'évaluation
