generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehFormEval
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_form_eval
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Liste des formulaires d'évaluation
        display: [titre]
        batch_actions: {}
        actions:
          _new: { label: Ajouter }
        object_actions:
          _edit: { label: Modifier }
          _delete: { label: Supprimer }
      filter:
        class: false
      form:
        fields:
          GessehCritere: { label: Critères }
      edit:
        title: Modifier %%titre%%
        actions:
          _delete: { label: Supprimer }
          _list: { label: Retour à la liste }
          addCriteria: { label: Ajouter un critère }
          _save: { label: Enregistrer }
      new:
        title: Nouveau formulaire d'évaluation
        actions:
          _list: { label: Retour à la liste }
          _save: { label: Enregistrer }
