<?php

namespace Gesseh\EvaluationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvalSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvalSectorRepository extends EntityRepository
{
  public function getEvalSectorQuery()
  {
    return $this->createQueryBuilder('s')
                ->join('s.form', 'f')
                ->join('f.criterias', 'c')
                ->join('s.sector', 't')
                ->addSelect('f')
                ->addSelect('c')
    ;
  }

  public function getEvalFormBySector($id)
  {
    $query = $this->getEvalSectorQuery();
    $query->where('t.id = :id')
            ->setParameter('id', $id)
          ->orderBy('c.rank', 'asc');

    return $query->getQuery()->getResult();
  }
}
