all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=gesseh'
      username: dbuser
      password: dbpassword
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=gesseh_test'
      username: dbuser
      password: dbpassword
