# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: terrain, action: index }

stage_index_tri:
  url: /tri/:tri1/:order1
  param: { module: terrain, action: index }

#stage_index_tri2:
#  url: /tri/:tri1/:order1/:tri2/:order2
#  param: { module: terrain, action: index }

stage_show:
  url: /stage/:id
  param: { module: terrain, action: show }
  requirements:
    id: \d+

#etudiant_index:
#  url: /etudiant/
#  param: { module: etudiant, action: index }

etudiant_edit:
  url: /etudiant/edit
  param: { module: etudiant, action: edit }

etudiant_update:
  url: /etudiant/update
  param: { module: etudiant, action: update }

etudiant_token:
  url: /etudiant/test/:userid/:token
  param: { module: etudiant, action: token }
  requirements:
    userid: \d+
    token: \w+

eval_index:
  url: /etudiant/
  param: { module: eval, action: index }

eval_show:
  url: /etudiant/:idstage
  param: { module: eval, action: show }
  requirements:
    idstage: \d+

eval_new:
  url: /etudiant/:idstage/new
  param: { module: eval, action: new }
  requirements:
    idstage: \d+

eval_create:
  url: /etudiant/:idstage/create
  param: { module: eval, action: create }
  requirements:
    idstage: \d+

