# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: services, action: index }

# generic rules
# please, remove them by adding more specific rules

gesseh_show_stage:
  url: /stage/:id
  param: { module: services, action: show }
  requirements:
    id: \d+

gesseh_index_monstage:
  url: /monstage/:iduser
  param: { module: monstage, action: index }
  requirements:
    iduser: \d+

gesseh_show_formulaire:
  url: /monstage/:iduser/:idstage
  param: { module: eval, action: show }
  requirements:
    iduser: \d+
    idstage: \d+

gesseh_new_formulaire:
  url: /monstage/:iduser/:idstage/new
  param: { module: eval, action: new }
  requirements:
    iduser: \d+
    idstage: \d+

gesseh_create_formulaire:
  url: /monstage/:iduser/:idstage/create
  param: { module: eval, action: create }
  requirements:
    iduser: \d+
    idstage: \d+

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
