# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: terrain, action: index }

terrain_index:
  url: /terrain/
  param: { module: terrain, action: index }

terrain_index_pager:
  url: /terrain/page/:page
  param: { module: terrain, action: index }
  requirements:
    page: \d+

terrain_index_tri:
  url: /terrain/tri/:col/:order
  param: { module: terrain, action: index }
  requirements:
    col: \w+
    order: \w+

#terrain_index_tri2:
#  url: /terrain/tri/:tri1/:order1/:tri2/:order2
#  param: { module: terrain, action: index }

terrain_show:
  url: /terrain/:id
  param: { module: terrain, action: show }
  requirements:
    id: \d+

etudiant_index:
  url: /etudiant/
  param: { module: etudiant, action: index }

etudiant_edit:
  url: /etudiant/edit
  param: { module: etudiant, action: edit }

etudiant_update:
  url: /etudiant/update
  param: { module: etudiant, action: update }

etudiant_token:
  url: /etudiant/test/:userid/:token
  param: { module: etudiant, action: token }
  requirements:
    userid: \d+
    token: \w+

eval_show:
  url: /eval/:idstage
  param: { module: eval, action: show }
  requirements:
    idstage: \d+

eval_new:
  url: /eval/:idstage/new
  param: { module: eval, action: new }
  requirements:
    idstage: \d+

eval_create:
  url: /eval/:idstage/create
  param: { module: eval, action: create }
  requirements:
    idstage: \d+

eval_show_terrain:
  url: /terrain/eval/:id
  param: { module: eval, action: terrain }
  requirements:
    id: \d+

choix_edit:
  url: /choix/
  param: { module: choix, action: edit }

choix_edit_up:
  url: /choix/:up/up
  param: { module: choix, action: edit }
  requirements:
    up: \d+

choix_edit_down:
  url: /choix/:down/down
  param: { module: choix, action: edit }
  requirements:
    down: \d+

choix_edit_del:
  url: /choix/:del/del
  param: { module: choix, action: edit }
  requirements:
    del: \d+

choix_update:
  url: /choix/update
  param: { module: choix, action: update }

choix_simul:
  url: /choix/simul/
  param: { module: choix, action: simul }

choix_simul_pager:
  url: /choix/simul/:debut
  param: { module: choix, action: simul }
  requirements:
    debut: \d+

choix_present:
  url: /choix/in
  param: { module: choix, action: present }

choix_absent:
  url: /choix/out
  param: { module: choix, action: absent }
