<?php

namespace Gesseh\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
  public function getStudentQuery()
  {
    return $this->createQueryBuilder('s')
                ->join('s.user', 'u')
                ->join('s.grade', 'p')
                ->addSelect('u')
                ->addSelect('p');
  }

  public function getById($id)
  {
    $query = $this->getStudentQuery();
    $query->where('s.id = :id')
          ->setParameter('id', $id);

    return $query->getQuery()
                 ->getSingleResult();
  }

  public function getAll()
  {
    $query = $this->getStudentQuery();
    $query->addOrderBy('s.surname', 'asc');
    $query->addOrderBy('s.name', 'asc');
    $query->addOrderBy('p.rank', 'asc');

    return $query->getQuery()
                 ->getResult();
  }
}
