<?php

namespace Gesseh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends EntityRepository
{
  public function getDepartmentQuery()
  {
    return $this->createQueryBuilder('d')->join('d.hospital', 'h')->join('d.sector', 's');
  }

  public function getById($id)
  {
    $query = $this->getDepartmentQuery();
    $query->where('d.id = :id')
          ->setParameter('id', $id);

    return $query->getQuery()->getSingleResult();
  }
}
