<?php

namespace Gesseh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HospitalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospitalRepository extends EntityRepository
{
  public function getHospitalQuery()
  {
    return $this->createQueryBuilder('h')
                ->join('h.departments', 'd')
                ->join('d.sector', 's')
                ->addSelect('d')
                ->addSelect('s');
  }

  public function getAll(array $orderBy = array ( 'h' => 'asc', 'd' => 'asc'))
  {
    $query = $this->getHospitalQuery();
    $query->addOrderBy('h.name', 'asc');
    foreach( $orderBy as $col => $order ) {
      $query->addOrderBy($col . '.name', $order);
    }

    return $query->getQuery()
                 ->getResult();
  }
}
