<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/15 00:59:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=10.0.0.1;dbname=gesseh',
  'username' => 'gesseh',
  'password' => 'cataract',
  'name' => 'doctrine',
)),);
