# src/Gesseh/CoreBundle/Resources/config/services.yml
services:
  gesseh_core.menu_builder:
    class: Gesseh\CoreBundle\Menu\MenuBuilder
    arguments: [@knp_menu.factory]

  gesseh_core.menu.anon:
    class: Knp\Menu\MenuItem
    factory_service: gesseh_core.menu_builder
    factory_method: createAnonMenu
    arguments: [@request]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: anon }

  gesseh_core.menu.student:
    class: Knp\Menu\MenuItem
    factory_service: gesseh_core.menu_builder
    factory_method: createStudentMenu
    arguments: [@request]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: student }

  gesseh_core.menu.admin:
    class: Knp\Menu\MenuItem 
    factory_service: gesseh_core.menu_builder
    factory_method: createAdminMenu
    arguments: [@request] 
    scope: request
    tags:
      - { name: knp_menu.menu, alias: admin }
