# src/Gesseh/CoreBundle/Resources/config/services.yml
services:
  gesseh_core.menu_builder:
    class: Gesseh\CoreBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory"]

  gesseh_core.menu.main:
    class: Knp\Menu\MenuItem
    factory: ["@gesseh_core.menu_builder", createMainMenu]
    arguments: ["@request_stack", "@security.authorization_checker", "@kdb_parameters.manager"]
    tags:
      - { name: knp_menu.menu, alias: main }

  gesseh_core.menu.anon:
    class: Knp\Menu\MenuItem
    factory_service: gesseh_core.menu_builder
    factory_method: createAnonMenu
    arguments: ["@request"]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: anon }

  gesseh_core.menu.student:
    class: Knp\Menu\MenuItem
    factory_service: gesseh_core.menu_builder
    factory_method: createStudentMenu
    arguments: ["@request"]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: student }

  gesseh_core.menu.admin:
    class: Knp\Menu\MenuItem
    factory_service: gesseh_core.menu_builder
    factory_method: createAdminMenu
    arguments: ["@request"]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: admin }

  gesseh_core.menu.teacher:
    class: Knp\Menu\MenuItem
    factory_service: gesseh_core.menu_builder
    factory_method: createTeacherMenu
    arguments: ["@request"]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: teacher }

  gesseh_core.menu.superteacher:
    class: Knp\Menu\MenuItem
    factory_service: gesseh_core.menu_builder
    factory_method: createSuperteacherMenu
    arguments: ["@request"]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: superteacher }
