generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehCritere
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_critere
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        type: { label: Type, help: radio pour une valeur chiffrée et text pour un commentaire }
        ratio: { label: Items, help: nombre de choix pour une valeur numérique }
      list:    
        title: Listing des critères de formulaires
        display: [=GessehFormEval, =titre, type, ratio]
        fields:
          GessehFormEval: { label: Formulaire }
        sort: [form, asc]
        batch_actions: {}
        object_actions:
          _edit: ~
      filter:
        display: [form, titre, type]
      form:    ~
      edit:
        title: Modifier %%titre%%
      new:
        title: Ajouter un critère d'évaluation à un formulaire
