generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehCritere
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_critere
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Listing des critères de formulaires
        display: [=form, =titre, type, ratio]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
