GessehHopital:
  actAs: {}
  columns:
    nom: { type: string(100), notnull: true, unique: true }
    adresse: { type: string(255), notnull: true }
    telephone: { type: string(14) }
    web: { type: string(255) }

GessehTerrain:
  actAs: {}
  columns:
    hopital_id: { type: integer, notnull: true }
    titre: { type: string(100), notnull: true }
    filiere: { type: integer, notnull: true }
    patron: { type: string(50), notnull: true }
    localisation: { type: string(255), notnull: false }
    gardes_lieu: { type: string(100), notnull: false }
    gardes_horaires: { type: string(100), notnull: false }
    astreintes_horaires: { type: string(100), notnull: false }
    total: { type: integer(3), notnull: true }
    page: { type: integer, notnull: false }
    is_active: { type: boolean, notnull: true, default: 1 }
  relations:
    GessehHopital: { onDelete: CASCADE, local: hopital_id, foreign: id }
    GessehFiliere: { local: filiere, foreign: id }
    GessehPage: { local: page, foreign: id }

GessehPage:
  actAs:
    Timestampable:
      created: { format: Y-m-d }
      updated: { format: Y-m-d }
    columns:
      contenu: { type: blob, notnull: false }

GessehFiliere:
  actAs: {}
  columns:
    titre: { type: string(100), notnull: true }
    form: { type: integer, notnull: false }
  relations:
    GessehFormEval: { local: form, foreign: id }

GessehEtudiant:
  actAs: 
    Timestampable:
      created: { disabled: true }
      updated: { format: Y-m-d }
  columns:
    nom: { type: string(50), notnull: true}
    prenom: { type: string(50), notnull: true }
    promo_id: { type: integer, notnull: true }
    classement: { type: integer, notnull: true }
    email: { type: string(50), notnull: true }
    token_mail: { type: string(50), notnull: true }
    tel: { type: string(14), notnull: false }
    naissance: { type: date, notnull: true }
    utilisateur: { type: integer, notnull: true }
  relations:
    GessehPromo:  { onDelete: CASCADE, local: promo_id, foreign: id }
    sfGuardUser: { onDelete: CASCADE, local: utilisateur, type: one, foreign: id }

GessehPromo:
  actAs: {}
  columns:
    titre: { type: string(100), notnull: true }
    ordre: { type: integer(2), notnull: true }
    form: { type: integer, notnull: false }
  relations:
    GessehFormEval: { local: form, foreign: id }

GessehStage:
  actAs: { Timestampable: ~ }
  columns:
    terrain_id: { type: integer, notnull: true }
    periode_id: { type: integer, notnull: true }
    etudiant_id: { type: integer, notnull: true }
    form: { type: integer, notnull: true }
    is_active: { type: boolean, notnull: true, default: 1 }
  relations:
    GessehTerrain:  { onDelete: CASCADE, local: terrain_id, foreign: id }
    GessehPeriode:  { onDelete: CASCADE, local: periode_id, foreign: id }
    GessehEtudiant:  { onDelete: CASCADE, local: etudiant_id, foreign: id }
    GessehFormEval: { local: form, foreign: id }

GessehPeriode:
  actAs: {}
  columns:
    titre: { type: string(20), notnull: true }
    debut: { type: date, notnull: true }
    fin: { type: date, notnull: true }

GessehFormEval:
  actAs: { Timestampable: ~ }
  columns:
    titre: { type: string(100), notnull: true }

GessehCritere:
  actAs: { Timestampable: ~ }
  columns:
    form: { type: integer, notnull: true }
    titre: { type: string(100), notnull: true }
    type: { type: string(10), notnull: true }
    ratio: { type: integer }
  relations:
    GessehFormEval:  { onDelete: CASCADE, local: form, foreign: id }

GessehEval:
  actAs: { Timestampable: ~ }
  columns:
    stage_id: { type: integer, notnull: true }
    critere_id: { type: integer, notnull: true }
    valeur: { type: string(255), notnull: true }
    created_at:
  relations:
    GessehStage:  { onDelete: CASCADE, local: stage_id, foreign: id }
    GessehCritere:  { onDelete: CASCADE, local: critere_id, foreign: id }

GessehChoix:
  actAs:
    Timestampable: ~
  columns:
    etudiant: { type: integer, notnull: true }
    poste: { type: integer, notnull: true }
    ordre: { type: integer(2), notnull: true }
  relations:
    GessehEtudiant: { onDelete: CASCADE, local: etudiant, foreign: id }
    GessehTerrain: { onDelete: CASCADE, local: poste, foreign: id }

GessehReferent:
  columns:
    utilisateur: { type: integer, notnull: true }
    promo: { type: integer, notnull: true }
    tel: { type: string(10), notnull: false }
    divers: { type: string, notnull: false }
  relations:
    GessehPromo: { onDelete: CASCADE, local: promo, foreign: id }
    sfGuardUser: { onDelete: CASCADE, local: utilisateur, foreign: id }

CopisimSimulation:
  columns:
    etudiant: { type: integer, notnull: true }
    poste: { type: integer, notnull: false }
    reste: { type: integer(2), notnull: false }
    absent: { type: boolean, notnull: true }
  relations:
    GessehEtudiant: { onDelete: CASCADE, local: etudiant, foreign: id }
    GessehTerrain: { local: poste, foreign: id }


