GessehHopital:
  actAs: { Timestampable: ~ }
  columns:
    nom: { type: string(255), notnull: true, unique: true }
    adresse: { type: string(255), notnull: true }
    telephone: { type: string(255) }
    web: { type: string(255) }

GessehTerrain:
  actAs: { Timestampable: ~ }    
  columns:
    hopital_id: { type: integer, notnull: true }
    filiere: { type: string(255), notnull: true }
    patron: { type: string(255), notnull: true }
    localisation: { type: string(255), notnull: true}
    gardes_lieu: { type: string(255), notnull: true}
    gardes_horaires: { type: string(255), notnull: true}
    astreintes_horaires: { type: string(255), notnull: true}
    is_active: { type: boolean, notnull: true, default: 1 }
  relations:
    GessehHopital: { onDelete: CASCADE, local: hopital_id, foreign: id }

GessehTerrainRule:
  actAs: { Timestampable: ~ }
  columns:
    terrain: { type: integer, notnull: true }
    promo: { type: integer, notnull: true }
    form: { type: integer, notnull: true }
  relations:
    GessehTerrain: { local: terrain, foreign: id }
    GessehPromo:  { local: promo, foreign: id }
    GessehCritere: { local: form, foreign: form }

GessehEtudiant:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, notnull: true, primary: true }
    nom: { type: string(255), notnull: true}
    prenom: { type: string(255), notnull: true }
    promo_id: { type: integer, notnull: true }
    email: { type: string(255), notnull: true }
    token_mail: { type: string(255), notnull: true }
    tel: { type: string(14), notnull: false }
  relations:
    GessehPromo:  { onDelete: CASCADE, local: promo_id, foreign: id }
    sfGuardUser: { local: id, foreign: username }

GessehPromo:
  actAs: { }
  columns:
    titre: { type: string(255), notnull: true }
    ordre: { type: integer(2), notnull: true }

GessehStage:
  actAs: { Timestampable: ~ }
  columns:
    terrain_id: { type: integer, notnull: true }
    periode_id: { type: integer, notnull: true }
    etudiant_id: { type: integer, notnull: true }
    form: { type: integer, notnull: true }
    is_active: { type: boolean, notnull: true, default: 1 }
  relations:
    GessehTerrain:  { onDelete: CASCADE, local: terrain_id, foreign: id }
    GessehPeriode:  { onDelete: CASCADE, local: periode_id, foreign: id }
    GessehEtudiant:  { onDelete: CASCADE, local: etudiant_id, foreign: id }
    GessehFormEval: { local: form, foreign: id }

GessehPeriode:
  actAs: { }
  columns:
    debut: { type: date, notnull: true }
    fin: { type: date, notnull: true }

GessehFormEval:
  actAs: { Timestampable: ~ }
  columns:
    titre: { type: string(255), notnull: true }

GessehCritere:
  actAs: { Timestampable: ~ }
  columns:
    form: { type: integer, notnull: true }
    titre: { type: string(255), notnull: true }
    type: { type: string(255), notnull: true }
    ratio: { type: integer }
  relations:
    GessehFormEval:  { onDelete: CASCADE, local: form, foreign: id }

GessehEval:
  actAs: { Timestampable: ~ }
  columns:
    stage_id: { type: integer, notnull: true }
    critere_id: { type: integer, notnull: true }
    valeur: { type: string(255), notnull: true }
    created_at:
  relations:
    GessehStage:  { onDelete: CASCADE, local: stage_id, foreign: id }
    GessehCritere:  { onDelete: CASCADE, local: critere_id, foreign: id }
