GessehHopital:
  actAs: { Timestampable: ~ }
  columns:
    nom: { type: string(255), notnull: true, unique: true }
    adresse: { type: string(255), notnull: true}
    telephone: { type: string(255)}
    web: { type: string(255)}

GessehTerrain:
  actAs: { Timestampable: ~ }    
  columns:
    hopital_id: { type: integer, notnull: true }
    filiere: { type: string(255), notnull: true}
    patron: { type: string(255), notnull: true}
    localisation: { type: string(255), notnull: true}
    form_id: { type: integer, notnull: true, default: 1 }
    is_active: { type: boolean, notnull: true, default: 1 }
  relations:
    GessehHopital: { onDelete: CASCADE, local: hopital_id, foreign: id }
    GessehCritere: { local: form_id, foreign: form }

GessehEtudiant:
  actAs: { Timestampable: ~ }
  columns:
    nom: { type: string(255), notnull: true}
    prenom: { type: string(255), notnull: true}
    promo_id: { type: integer, notnull: true }
    email: { type: string(255), notnull: true}
  relations:
    GessehPromo:  { onDelete: CASCADE, local: promo_id, foreign: id }

GessehPromo:
  actAs: { Timestampable: ~ }
  columns:
    titre: { type: string(255), notnull: true}

GessehStage:
  actAs: { Timestampable: ~ }
  columns:
    terrain_id: { type: integer, notnull: true }
    periode_id: { type: integer, notnull: true }
    etudiant_id: { type: integer, notnull: true }
    is_active: { type: boolean, notnull: true, default: 1 }
  relations:
    GessehTerrain:  { onDelete: CASCADE, local: terrain_id, foreign: id }
    GessehPeriode:  { onDelete: CASCADE, local: periode_id, foreign: id }
    GessehEtudiant:  { onDelete: CASCADE, local: etudiant_id, foreign: id }

GessehPeriode:
  actAs: { Timestampable: ~ }
  columns:
    debut: { type: date, notnull: true }
    fin: { type: date, notnull: true }

GessehCritere:
  actAs: { Timestampable: ~ }
  columns:
    form: { type: integer, notnull: true }
    titre: { type: string(255), notnull: true }
    type: { type: string(255), notnull: true }

GessehEval:
  actAs: { Timestampable: ~ }
  columns:
    stage_id: { type: integer, notnull: true }
    critere_id: { type: integer, notnull: true }
    valeur: { type: string(255), notnull: true }
    created_at:
  relations:
    GessehStage:  { onDelete: CASCADE, local: stage_id, foreign: id }
    GessehCritere:  { onDelete: CASCADE, local: critere_id, foreign: id }
    
GessehParam:
  actAs: { Timestampable: ~ }
  columns:
    titre: { type: string(255), notnull: true }
    valeur: { type: string(255), notnull: true }
