generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehSimulation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_simulation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        etudiant: { label: Étudiant }
        gesseh_etudiant: { label: Étudiant }
        poste: { label: Poste validé }
        gesseh_terrain: { label: Poste validé }
      list:
        title: Simulation de choix de poste
        display: [gesseh_etudiant, gesseh_terrain, reste, absent]
        max_per_page: 50
        actions:
          simul: { label: Lancer la simulation }
#          ignore: { label: Afficher la liste choix ignorés }
          valid: { label: Valider la simulation }
          update: { label: Définir la table de simulation }
        batch_actions: {}
        object_actions: {}
#          stages: { label: Stages effectués }
      filter:
        display: [reste, absent]
      form:    ~
      edit:    ~
      new:     ~
