generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehStage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_stage
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        is_active: { label: Non évalué }
      list:
        title: "Liste d'affectation des stages"
        display: [=gesseh_periode, gesseh_terrain, gesseh_etudiant, is_active]
        fields:
          gesseh_periode: { label: "Période" }
          gesseh_terrain: { label: "Terrain de stage" }
          gesseh_form_eval: { label: "Formulaire d'évaluation" }
          gesseh_etudiant: { label: "Etudiant" }
        batch_actions: {}
        object_actions:
          _edit: { label: "Modifier" }
        actions:
          _new: { label: "Ajouter" }
          mailRappel: { label: "Mail de rappel (évaluations non faites)", help: "Mail de rappel à tous les étudiants n'ayant pas évalué leur stage" }
#          importStages: { label: "Importer l\'attribution des stages" }
        table_method: retrieveAdminStageList
        max_per_page: 50
#        sort: []
      filter:
        display: [periode_id, etudiant_id, is_active]
      form: ~
      edit:
        title: "Edition du stage"
      new:
        title: "Ajout d'un stage"
